- chainio/constructor/constructor.go
blsoperatorstateretriever was getting fetched wrong
Fixes # .
> fix bug in constructor

- chainio/constructor/constructor.go
> need to export config fields to be usable

- chainio/elcontracts/writer.go
Fixes # .
Fixing bug where operator update doesn't update delegation approver address
Added mapping
> bug: fix bug in update operator details

- crypto/ecdsa/utils.go
- crypto/ecdsa/utils_test.go
- metrics/collectors/economic/economic.go
Fixes # .
Export methods to save and retrieve ecdsa keys
> add ecdsa utility methods

- chainio/constructor/constructor.go
> set promreg

- types/operator.go
- types/operator_test.go
Fixes #29 
Also added a body.Close() fix
> fix for delegation approver address

- services/bls_aggregation/blsagg_test.go
> fixed race condition in test

- cmd/egnkey/main.go
- cmd/egnkey/store.go
- crypto/ecdsa/utils.go
Fixes #67  .
@shrimalmadhur let me know what you think. Couldn't figure out how you generated these files, so I went ahead and added this functionality. Did you have another (simpler?) way of doing this already?
> implemented store command for ecdsa

- metrics/collectors/economic/economic.go
> skip metrics collection when oeprator has not registered yet

- CONTRIBUTING.md
Fixes # .
Update contribution guideline to have forking guidance
> update contribution guideline

- Makefile
> remove coverage flag from test command in makefile

- chainio/clients/avsregistry/writer.go
> just changes name and added comment to explaining registering stuff

- chainio/clients/avsregistry/writer.go
- chainio/clients/builder.go
- logging/slog_logger.go
- logging/zap_logger.go
- types/errors.go
Fixes # .
Add basic slog implementation
> add slog implementation

- chainio/mocks/avsRegistryContractsWriter.go
> update avsregistrywriter mock

- crypto/bls/attestation.go
> added GetOperatorID function

- chainio/clients/avsregistry/reader.go
- chainio/clients/avsregistry/subscriber.go
- chainio/clients/avsregistry/writer.go
- chainio/clients/builder.go
- chainio/clients/elcontracts/reader.go
- chainio/clients/elcontracts/writer.go
- chainio/clients/eth/client.go
- chainio/clients/eth/instrumented_client.go
- chainio/clients/fireblocks/list_vault_accounts.go
- chainio/clients/mocks/fireblocks.go
- chainio/clients/txsender/fireblocks_txsender.go
- chainio/clients/txsender/fireblocks_txsender_test.go
- chainio/clients/txsender/privatekey_txsender.go
- chainio/utils/bindings.go
- signer/basic_signer.go
This PR introduces Fireblocks TxSender which uses fireblocks client to implement an MPC tx sender
> [HotWallet] Implement Fireblocks TxSender

- chainio/clients/builder.go
- chainio/clients/wallet/fireblocks_txsender.go
- chainio/clients/wallet/fireblocks_txsender_test.go
- chainio/clients/wallet/privatekey_txsender.go
- chainio/clients/wallet/txsender.go
- chainio/txmgr/txmgr.go
Renames `txsender` to `wallet`
> [HotWallet] Rename `txsender` to `wallet`

- chainio/clients/wallet/privatekey_txsender.go
Bug submitted by Uri from lightblocks.
> make contracts struct in privatekey-txsender constructor

- chainio/clients/builder.go
> remove hardcoded chainid in clients builder

- services/operatorpubkeys/operatorpubkeys_inmemory.go
Just a small cleanup logs/comments PR.
> fix outdated logs and comments in operatorpubkeys service

- chainio/clients/fireblocks/client.go
- chainio/clients/wallet/fireblocks_wallet.go
Adds Fireblocks asset ID `ETH_TEST6` for Holesky testnet
> Add holesky asset ID for Fireblocks client

- logging/logger.go
- logging/noop_logger.go
- logging/slog_logger.go
- logging/zap_logger.go
`With` method can be used to create child logger with default tags
> [logger] Add `With` method for creating child logger

- types/operator_metadata.go
- types/operator_metadata_test.go
Fixes # .
- remove FTP for url validation
> remove ftp

- types/errors.go
- types/operator_metadata.go
- types/operator_metadata_test.go
- utils/utils.go
Fixes # .
- Add more strict `twitter` and `x` validations
> better twitter validation

- types/errors.go
- types/operator_metadata.go
- types/operator_metadata_test.go
Fixes # .
- Adds better validation for name and description
> better validation for name and description

- types/errors.go
- types/operator.go
- types/operator_metadata.go
- types/operator_metadata_test.go
- types/operator_test.go
- utils/errors.go
- utils/utils.go
- utils/utils_test.go
Fixes # .
- Add checks so that there's no redirect
- Add Github validation which should be used by cli and webserver
- Bunch of refactor
> validate urls

- types/operator.go
- types/operator_metadata_test.go
- utils/errors.go
- utils/utils.go
Fixes # .
- Fix method name
- allow 500 character
- limit public url to 1 MiB
> change logic

- utils/utils.go
> add + to our regex

- chainio/clients/wallet/fireblocks_wallet.go
- chainio/clients/wallet/fireblocks_wallet_test.go
Adds `ErrNotYetBroadcasted` to indicate that the transaction is still being processed by Fireblocks without having been published in the network.
Callers can use this information to customize logic that waits for the transaction receipt.
> [fireblocks] Return specific err for prebroadcast status

- chainio/clients/avsregistry/reader.go
- services/bls_aggregation/blsagg.go
> small fixes

- README.md
- chainio/clients/avsregistry/writer.go
- chainio/clients/elcontracts/writer.go
- cmd/egnaddrs/main.go
- cmd/egnkey/generate.go
- services/avsregistry/avsregistry_chaincaller_test.go
- services/bls_aggregation/blsagg.go
- types/operator_test.go
Adds go report card badge to the repo, fix report card issues. closes ELD-187
> Add Go Report Card Badge

- services/bls_aggregation/blsagg.go
Had 3 fatals in the blsagg service.
Changed to return errors to client instead.
> removed all fatals from blsagg service

- chainio/clients/avsregistry/reader.go
- chainio/clients/avsregistry/writer.go
- services/operatorsinfo/operatorsinfo_inmemory.go
- types/operator.go
socket event filter iterator logic was totally wrong so was returning 0 results. Fixed it here.
Also added some other cosmetic changes.
> Fix operatorsinfo socket bugs

- .github/workflows/check-mocks.yml
> add check-mocks github workflow

- .gitmodules
- contracts/bindings/IRewardsCoordinator/binding.go
- contracts/generate-bindings.sh
Fixes # .
- Add rewards coordinator binding
- Fix submodule link
> [ELO-184] add reward coordinator bindings
