Layr-Labs/eigensdk-go

chainio/constructor/constructor.go
Small change. Just found it confusing when creating the constructor config in eigenDA repo.
=> changed prom metrics ipportaddr name

chainio/avsregistry/reader.go, chainio/clients/avs_registry_contracts_client.go, chainio/constructor/constructor.go, chainio/mocks/avsRegistryContractClient.go, chainio/mocks/avsRegistryContractsReader.go, metrics/collectors/economic.go, metrics/collectors/economic_test.go, metrics/eigenmetrics_example_test.go, types/Operator.go
=> updated economic metrics to reflect new spec

chainio/clients/eth/instrumented_client.go, chainio/constructor/constructor.go, metrics/collectors/economic/economic.go, metrics/collectors/economic/economic_test.go, metrics/collectors/rpc_calls/rpc_calls.go, metrics/collectors/rpc_calls/rpc_calls_test.go, metrics/eigenmetrics.go, metrics/eigenmetrics_example_test.go, metrics/eigenmetrics_test.go, metrics/metrics.go, metrics/noop_metrics.go
this removes circular dependencies and makes it cleaner
Fixes # .
=> separated rpc call metrics into a collector

chainio/elcontracts/writer.go, crypto/bls/attestation.go, crypto/bn254/utils.go
bls pubkey compendium registration logic was changed to also require signing over the bls pubkey compendium's address, so updated the offchain logic to also include this.
=> fixed registration logic

chainio/avsregistry/reader.go, chainio/clients/avs_registry_contracts_client.go, chainio/mocks/avsRegistryContractClient.go, chainio/mocks/avsRegistryContractsReader.go, metrics/collectors/economic/economic.go, metrics/collectors/economic/economic_test.go, services/avsregistry/avsregistry_chaincaller.go
eigenDA team was running into errors because the economicCollector was fetching operatorId from the eigenda registry coordinator in its constructor, which is initialized before the node starts. When the operator is registered at node start, it only registers in the start() function, which happens after, so the economicCollector never gets updated with the operatorId and hence keeps erroring on the collect call.
This PR moves fetching the operatorId into the collector. This adds 1 round trip latency to the node on every collect (every ~15sec), but at least this will fix this problem. Another solution might be to cache the operatorId after one of the collect calls gets the operatorId, but this *could* break if we later allow the operatorId to change.
=> now fetching operatorId dynamically in economicCollector

chainio/avsregistry/reader.go, chainio/elcontracts/writer.go, crypto/bls/attestation.go, crypto/bn254/utils.go, utils/utils.go
Fixes # .
- Fix log message for `ReadYamlConfig` method
- formatting change
=> nit: fix log message

types/operator_metadata.go, types/operator_metadata_test.go
Fixes # .
We only want to allow `png` image upload to reduce surface are of image validation. IF we need other image format like jpg/jpeg, we can add that later.
- Update validation
- Add tests
=> update metadata to only allow png images

cmd/egnkey/README.md, cmd/egnkey/generate.go
Fixes # .
1. Create ECDSA and BLS keys using both key-type 
2. Prefix UUID folder name with ecdsa- and bls- to know the dir type
1. Move some methods to common
2. Add key-type both
=> [EgnKey] Generate ECDSA and BLS keys with both-key-type

nodeapi/nodeapi.go, nodeapi/nodeapi_test.go
=> updated nodeapi

crypto/bls/attestation.go
Fixes # .
Right now if you put ecdsa key file in place of bls key, it creates a new pair and carries on
We want to put validation so that correct file is used for creating correct key. I am not sure if there's a better way to validate bls key file content which we generate.
=> validate bls key file contents

chainio/clients/avsregistry/reader.go
- `isOperatorRegistered()` was using the operator ID to determine if an operator is registered
- This was an issue because after an operator de-registers from an AVS, their operator info and ID is not removed from the registry coordinator so `isOperatorRegistered()` was still returning `true`
- Fixes `isOperatorRegistered()` so it uses operator status instead of operator ID to determine if an operator is registered
Tested this with the CLI in `incredible-squaring-avs` and verified that we're getting the correct value now for `registeredWithAvs`.
=> Fix isOperatorRegistered

chainio/clients/avsregistry/reader.go, chainio/clients/avsregistry/subscriber.go, chainio/clients/avsregistry/writer.go, chainio/clients/builder.go, chainio/clients/elcontracts/reader.go, chainio/utils/bindings.go, metrics/collectors/economic/economic.go, metrics/eigenmetrics.go, nodeapi/nodeapi.go, services/avsregistry/avsregistry_chaincaller.go, services/bls_aggregation/blsagg.go, signer/basic_signer.go, types/errors.go, types/operator.go, types/operator_metadata.go, types/operator_metadata_test.go, types/operator_test.go
some avs teams who are forking our clients and remove some contracts such as the apkRegistry end up with bugs here, and the errors were not informative, so added logging lines for them.
=> added error logs for avs reader/writer clients

chainio/clients/avsregistry/writer.go, chainio/clients/elcontracts/writer.go, chainio/txmgr/txmgr.go, signer/basic_signer.go, utils/utils.go
Here's an example output from running avs-sync
Funnily enough, neither of the two txHash printed is the correct one, which was extremely confusing haha.
Changed it so that everywhere we only print txHash of txs that are successfully included in the chain.
=> we were printing tx hash of half-built transactions, which was pointless

cmd/egnaddrs/main.go, cmd/egnkey/generate.go
Fixes a small TODO in the code for a little bit more descriptive description of the `egnaddrs`:
https://github.com/Layr-Labs/eigensdk-go/blob/a5629b0ff188bbc876a1da705b5c4cd96ff8b7f0/cmd/egnaddrs/main.go#L50
To change it from this: 
https://github.com/Layr-Labs/eigensdk-go/blob/a5629b0ff188bbc876a1da705b5c4cd96ff8b7f0/cmd/egnaddrs/main.go#L51
To this: 
```go
app.Description = "This utility facilitates the debugging and testing of Eigenlayer and AVS contract deployments by retrieving and displaying a comprehensive list of contract addresses. Starting from an initial contract address provided, it recursively identifies and prints addresses for all relevant Eigenlayer and AVS contracts within the network. This includes service managers, registry coordinators, and various registries, thus …
```
=> Enhance description of egnaddrs utility for better clarity

cmd/egnkey/generate.go
Fixes a TODO in the code: 
https://github.com/Layr-Labs/eigensdk-go/blob/a5629b0ff188bbc876a1da705b5c4cd96ff8b7f0/cmd/egnkey/generate.go#L76
Updating to a factory pattern is smart to decouple object creation from its usage in our key generation logic. This change addresses the challenge of supporting multiple key types (ECDSA and BLS) in a scalable way. 
The first I did was to include a KeyGenerator interface and two concrete implementations for ECDSA and BLS key types. The factory function, NewKeyGenerator, dynamically selects the appropriate generator based on input parameters, simplifying the generate function.
Would someone mind if we wrote unit tests for the newly implemented factory pattern in our key generation system, particularly focusing on the dynamic selection logic of the …
=> Improved key generation with factory pattern

chainio/txmgr/txmgr.go
`EthBackend` shares methods with `eth.Client`.
This PR removes `EthBackend` and replaces it with `eth.Client`.
=> Replace `EthBackend` to `eth.Client` in `txmgr`

logging/slog_logger.go
Started looking into slog:
- https://go.dev/blog/slog
- https://www.youtube.com/watch?v=8rnI2xLrdeM
and agree with @dmanc at this point that we should probably start adopting slog as our standard logger everywhere. Been playing with it a bit and our current interface is super limiting wrt what can be done with slog (for eg can't pass a context to logging functions right now, which can be used to also log traceIds). The blog above mentions this
This draft PR is a wip for adding features to the slogger itself. But we'll eventually need to find a way to adapt our main interface, probably in a next PR. This will require more discussions.
Features added thus far:
- Only print required log level (production logger will only print info and above logs, whereas the development one will also print …
=> Updates to slog to make it the default feature-full logger

chainio/clients/avsregistry/reader.go, chainio/clients/avsregistry/writer.go, chainio/mocks/avsRegistryContractsReader.go, chainio/mocks/avsRegistryContractsWriter.go, chainio/txmgr/txmgr.go, crypto/bls/data.go, services/avsregistry/avsregistry.go, services/avsregistry/avsregistry_chaincaller.go, services/avsregistry/avsregistry_chaincaller_test.go, services/avsregistry/avsregistry_fake.go, services/bls_aggregation/blsagg.go, services/bls_aggregation/blsagg_test.go, services/mocks/avsregistry.go, services/mocks/blsagg/blsaggregation.go, services/operatorpubkeys/operatorpubkeys_inmemory.go, types/avs.go, types/basic.go, types/operator.go, utils/utils.go
Some of our core types were hard to read because they were logged as base64 encoded values, or just long byte strings.
This PR creates a few new basic types that have slog LogValues to print them in a more human-readable way.
=> Add basic types with slog logvalues

chainio/clients/builder.go, chainio/clients/elcontracts/writer.go, chainio/txmgr/txmgr.go
Removing signer from `TxManager` so that it's agnostic to the type of `wallet`. 
`TransactOpts` will be populated when the transaction is broadcasted in `TxManager.wallet`.
=> Remove signer from txn manager

chainio/clients/fireblocks/client.go, chainio/clients/fireblocks/client_test.go, chainio/clients/fireblocks/contract_call.go, chainio/clients/fireblocks/get_asset_addresses.go, chainio/clients/mocks/fireblocks.go, chainio/clients/mocks/wallet.go, chainio/clients/wallet/fireblocks_wallet.go, chainio/clients/wallet/fireblocks_wallet_test.go, chainio/clients/wallet/privatekey_wallet.go, chainio/clients/wallet/wallet.go
This PR adds a `SenderAddress` method to `Wallet` interface, which returns the address of the sender.
It also set a `HIGH` gas fee (configured by Fireblocks) to increase the chance of transactions being confirmed sooner.
=> [Hotwallet] Return sender address & set gas fee

chainio/clients/fireblocks/contract_call.go, chainio/clients/fireblocks/get_transaction.go, chainio/clients/fireblocks/status.go, chainio/clients/wallet/fireblocks_wallet.go, chainio/clients/wallet/fireblocks_wallet_test.go, chainio/txmgr/txmgr.go
- Renamed `Status` with `TxStatus` to make it clear that it only applies to transaction status
- Fixed a bug in fireblocks wallet `getWhitelistedContract` method where it was returning the last contract instead of the contract that matches the condition
- Fixed a bug in txmgr `queryReceipt` method which was transforming `txID` into a hash (this only worked for private key wallet)
=> Few fixes on `Wallet` implementation

chainio/clients/wallet/fireblocks_wallet.go
`fireblockTx.TxHash` isn't available if the transaction has not been broadcasted to the network. We don't need to specify `replaceTxByHash` in this case.
=> [Fireblocks] Don't replace transaction if txHash not available

chainio/clients/fireblocks/client_test.go, chainio/clients/fireblocks/contract_call.go, chainio/clients/wallet/fireblocks_wallet.go, chainio/clients/wallet/fireblocks_wallet_test.go
It used to rely on Fireblocks' gas estimation by passing in `HIGH` as `feeLevel` parameter when creating a transaction.
However, this estimation doesn't guarantee that replacement (boosting) transaction increases the gas cost by > 15% than the previous transaction, which is a requirement for replacing a pending transaction. 
We need to explicitly pass in the gas fee cap and priority fee cap instead of passing in `feeLevel` in this case.
=> [Fireblocks] Pass in gas info when calling contract

chainio/clients/wallet/privatekey_wallet.go, chainio/txmgr/txmgr.go
See https://github.com/Layr-Labs/eigensdk-go/pull/165#issuecomment-2025966763
=> Move estimateGasAndNonce from wallet to txMgr, and add gasLimit 1.1x bump by default

chainio/clients/wallet/fireblocks_wallet.go, chainio/clients/wallet/fireblocks_wallet_test.go
Apparently, Fireblocks expects gas fees to be in gwei (instead of wei)
=> [fireblocks] Convert gas units to gwei

chainio/clients/avsregistry/reader.go
Got this error when running on holesky (previously we were only running on anvil so not seeing these limitations)
```
panic: Cannot filter logs: 413 Request Entity Too Large: {"jsonrpc":"2.0","id":12,"error":{"code":-32614,"message":"eth_getLogs is limited to a 10,000 range"}}
```
=> fix getLogs call pagination by querying for 10_000 blocks at a time

chainio/clients/avsregistry/reader.go
`i.Add(i, big.NewInt(10_000))` increments i, so while printing we were also causing i to get incremented...
also fixed the toBlock which could have been bigger on the last iteration
=> fix bigint bug

chainio/clients/avsregistry/writer.go, chainio/clients/elcontracts/writer.go
Removing space from log attribute labels
=> Fix log label from `tx hash` to `txHash`

types/errors.go, types/operator_metadata.go
Adds proper error message if operator logo from metadata could not be fetched (404 error for example). 
Previously if logo could not be fetched user would receive mime type error that only pngs are supported
Check for http response status and throw self explanatory error
=> feat: return metadata logo fetch error

logging/zap_logger.go
For a zap logger wrapper, if not contain the `AddCallerSkip`, it 's caller will be the log func 's pos:
```log
2024-04-04T15:59:14.151+0800    DEBUG   logging/zap_logger.go:45        List of queried operator registration events in blsApkRegistry{"alreadyRegisteredOperatorAddr": ["0xe9a7669ac9ebe9b7e21e0a323fc3a6f34ce744eb"], "service": "OperatorPubkeysServiceInMemory"}
2024-04-04T15:59:14.151+0800    INFO    logging/zap_logger.go:69        Starting aggregator.
2024-04-04T15:59:14.151+0800    INFO    logging/zap_logger.go:69        Starting aggregator rpc server.
2024-04-04T15:59:14.151+0800    INFO    logging/zap_logger.go:49        Aggregator set to send new task every 10 seconds...
2024-04-04T15:59:14.151+0800    INFO    logging/zap_logger.go:49        Start LegacyRpcServer   {"addr": …
```
=> Fix: Add AddCallerSkip for zap to show real caller

services/avsregistry/avsregistry_chaincaller.go, types/errors.go
Note in:
```go
func (ar *AvsRegistryServiceChainCaller) getOperatorPubkeys(ctx context.Context, operatorId types.OperatorId) (types.OperatorPubkeys, error) {
operatorAddr, err := ar.AvsRegistryReader.GetOperatorFromId(&bind.CallOpts{Context: ctx}, operatorId)
if err != nil {
return types.OperatorPubkeys{}, types.WrapError(errors.New("Failed to get operator address from pubkey hash"), err)
}
pubkeys, ok := ar.operatorPubkeysService.GetOperatorPubkeys(ctx, operatorAddr)
if !ok {
return types.OperatorPubkeys{}, fmt.Errorf("Failed to get operator pubkeys from pubkey compendium service (operatorAddr: %v, operatorId: %v)", operatorAddr, operatorId)
}
return pubkeys, nil
}
```
if `operatorPubkeysService` not found the key, it will return false but the `err` is nil, it will cause a panic by read …
=> Fix:  Error wrap may panic by nil error

services/bls_aggregation/blsagg.go, services/bls_aggregation/blsagg_test.go
An AVS can have multi-quorum, but if one operator not stake in all quorums, the `checkIfStakeThresholdsMet` will panic by not check if operator stake for a quorum.
In Code:
```golang
// checkIfStakeThresholdsMet checks at least quorumThresholdPercentage of stake
// has signed for each quorum.
func checkIfStakeThresholdsMet(
signedStakePerQuorum map[types.QuorumNum]*big.Int,
totalStakePerQuorum map[types.QuorumNum]*big.Int,
quorumThresholdPercentagesMap map[types.QuorumNum]types.QuorumThresholdPercentage,
) bool {
// Just for show case
fmt.Printf("signedStakePerQuorum %v\n", signedStakePerQuorum)
fmt.Printf("totalStakePerQuorum %v\n", totalStakePerQuorum)
fmt.Printf("quorumThresholdPercentagesMap %v\n", quorumThresholdPercentagesMap)
for quorumNum, quorumThresholdPercentage := range …
```
=> Fix: Not panic when call checkIfStakeThresholdsMet for operator which not stake all quorum

types/errors.go
Wrapping errors using `%s` formats the error message, but does not wrap the error in a way that can be unwrapped by `errors` library. Using `%w` allows child errors to be unwrapped properly.
=> Wrap error properly

chainio/clients/fireblocks/cancel_transaction.go, chainio/clients/fireblocks/client.go, chainio/clients/fireblocks/client_test.go, chainio/clients/fireblocks/get_asset_addresses.go, chainio/clients/fireblocks/get_transaction.go, chainio/clients/mocks/fireblocks.go, chainio/clients/wallet/fireblocks_wallet.go
Adding support for canceling transaction in flight. 
This method can cancel transactions that have not been broadcasted to the network (either because it's still gathering cosignatures or other MPC operations)
=> [fireblocks] Add a way to cancel transaction

chainio/utils/bindings.go, contracts/bindings/IndexRegistry/binding.go, contracts/generate-bindings.sh
Fixes #200  .
Sometimes we need get operator list from IndexRegistry for some purpose, but realize that sdk doesn't contain bindings for IndexRegistry contract right now.
Modify `generate-bindings.sh` a bit and ask it generate everything for us : D
=> fix: generate go binding for IndexRegistry

services/bls_aggregation/blsagg.go, services/bls_aggregation/blsagg_test.go
task expiration timer was not being stopped upon task completion, so was returning unwanted errors.
Also error was not tagged with taskIndex so was impossible to know which taskId had expired.
=> fix task expiration timer: was not being stopped on task completion

chainio/clients/builder.go
Updated avs subscriber constructor yesterday but forgot to update the builder, so was passing the wrong contract address.
=> fix bug in builder

.github/PULL_REQUEST_TEMPLATE.md, go.mod, go.sum, logging/slog_logger.go, services/operatorsinfo/operatorsinfo_inmemory_test.go
Fixes # .
- add colored logs to slog text logger
- deprecated old constructors in favor of new ones that have our own options
=> updates to slogger constructors (text handler now has colored logs)

chainio/clients/fireblocks/contract_call.go, chainio/clients/wallet/fireblocks_wallet.go, chainio/clients/wallet/fireblocks_wallet_test.go
`externalTxID` serves as an idempotency key.
An issue with Fireblocks `externalTxID` is that even when the `ContractCall` request fails (i.e. due to timeout) their DB still saves the `externalTxID`, which invalidates any further retries with the same `externalTxID`. With the information available in `types.Transaction`, there isn't reliable way to determine if the request is a retry or not.
=> [fireblocks] Leave `externalTxID` empty

chainio/txmgr/txmgr.go
Fixes # .
- Remove double multiplication of `gasLimit`
=> fix: remove double multiplication

utils/errors.go, utils/utils.go, utils/utils_test.go
Fixes # .
- Return better error to user
- `make fmt`
=> better error returned

chainio/clients/avsregistry/reader.go
Fixes # .
Since FilterQuery is inclusive (as discussed [here](https://ethereum.stackexchange.com/questions/78620/is-the-range-of-a-filterquery-inclusive-up-to-toblock)) to toBlock there were duplicates in every iteration, for example: [0,10000], [10000, 20000]
Would get block 10000 twice.
- [] Code deprecates any old functionality before removing it
=> fix: duplicate operatorAddresses, operatorPubkeys caused by inclusive FilterQuery

chainio/clients/fireblocks/client.go, chainio/clients/fireblocks/client_test.go, chainio/clients/fireblocks/list_external_accounts.go, chainio/clients/fireblocks/transaction.go, chainio/clients/fireblocks/transfer.go, chainio/clients/mocks/fireblocks.go, chainio/clients/wallet/fireblocks_wallet.go, chainio/clients/wallet/fireblocks_wallet_test.go
This PR adds a transfer functionality to Fireblocks wallet.
=> [fireblocks] Add transfer method

services/operatorsinfo/operatorsinfo_inmemory.go
simplest PR that was ever created.
this results in printing hex operatorId (which is actually useful for debugging) instead of byte array (useless and clutters logs)
=> clean operatorId output (prints as hex instead of byte array)

chainio/clients/avsregistry/writer.go, chainio/clients/builder.go
=> feat: make bindings, wallet and txManager available

chainio/clients/eth/instrumented_client.go, chainio/txmgr/txmgr.go, crypto/bn254/utils.go, metrics/README.md, metrics/collectors/economic/economic.go, metrics/eigenmetrics.go, metrics/metrics.go, nodeapi/README.md, nodeapi/nodeapi.go, nodeapi/nodeapi_example_test.go, nodeapi/nodeapi_test.go
=> fix: broken links for nodeapi

aws/config.go, aws/kms/client.go, aws/kms/get_public_key.go, aws/kms/get_public_key_test.go, aws/kms/get_signature.go, cmd/egnaddrs/main_test.go, go.mod, go.sum, signerv2/kms_signer.go, signerv2/kms_signer_test.go, testutils/anvil.go, testutils/localstack.go
This PR adds a signer with a KMS key. 
- `aws/kms`: KMS client, methods to retrieve public key and create signatures using a key
- `testutils`: moved methods for creating containers (localstack, anvil) to this package 
- `signerv2`: implemented new signer `KMSSigner`
=> Add KMS Signer

crypto/bn254/utils.go, signerv2/config.go, signerv2/remote_signer_client.go, signerv2/signer.go, signerv2/web3_signer.go, utils/utils.go
Fixes # .
- Implement remote web3 signer
=> implement web3 signer

types/operator_metadata_test.go, utils/utils.go
Fixes # .
- Add `%` to the text regex
=> add % to regex

chainio/clients/avsregistry/reader.go, chainio/mocks/avsRegistryContractsReader.go, services/operatorsinfo/operatorsinfo_inmemory.go, services/operatorsinfo/operatorsinfo_inmemory_test.go
Realized some node providers don't even allow the 10k query range, so had to make it passed as an argument, with default fallback to 10_000.
This is another breaking change for the interface though :\
=> make queryBlockRangea an argument to query log functions

services/operatorsinfo/operatorsinfo_inmemory.go
created on top of #238 so should merge that first, which will simplify this PR.
=> Oprs info parallel query

services/operatorsinfo/operatorsinfo_subgraph.go, services/operatorsinfo/operatorsinfo_subgraph_test.go
Fixes # .
Adds unit + integration tests for operatorInfo subgraph
=> AVS-259: Subgraph test

.gitmodules, services/operatorsinfo/integration_test_deployment/.github/workflows/test.yml, services/operatorsinfo/integration_test_deployment/.gitignore, services/operatorsinfo/integration_test_deployment/BLSApkRegistryMock.sol, services/operatorsinfo/integration_test_deployment/README.md, services/operatorsinfo/integration_test_deployment/deployment_script.sol, services/operatorsinfo/integration_test_deployment/foundry.toml, services/operatorsinfo/integration_test_deployment/script/Counter.s.sol, services/operatorsinfo/integration_test_deployment/script/deployment_script.s.sol, services/operatorsinfo/integration_test_deployment/src/Counter.sol, services/operatorsinfo/integration_test_deployment/test/BLSApkRegistryMock.sol, services/operatorsinfo/integration_test_deployment/test/Counter.t.sol, services/operatorsinfo/operatorsinfo_subgraph.go, services/operatorsinfo/operatorsinfo_subgraph_integration_test.go, services/operatorsinfo/operatorsinfo_subgraph_test.go
=> Subgraph testing

metrics/eigenmetrics.go
This PR does following:
- introduces new server mux instead of default
- uses context from `Start` to be able to stop server// context handling
- `context` arg was currently not being used
- in our e2e tests, we create multiple metric servers (for different services/components/multiple operators). We couldn't register different prometheus registries because of the `DefaultServeMux` coming from `http` package. This change could enable that
=> feat: use new NewServeMux instead of Default and ctx for running metrics server

services/operatorsinfo/operatorsinfo_inmemory.go
Simple change. Tried to find a way to get slog to pass map keys through their LogValue function, but couldn't find anything.
Another option would be to define a custom type for each map we have and define a LogValue on each, but that seems tiresome...
=> fix the way operator sockets are printed in operatorsinfo srvc

services/bls_aggregation/blsagg.go, services/bls_aggregation/blsagg_test.go, types/avs.go
Fixes [AVS-218](https://linear.app/eigenlabs/issue/AVS-218/fix-blsagg-service-to-store-and-return-msgs-not-their-hash)
Update `bls_aggregation` service to return the Task Response bytes 
- Added the type `TaskResponse` to the avs types and include it in the `BlsAggregationServiceResponse`
- Update `ProcessNewSignature` to take in the `TaskResponse` as a parameter instead of the `TaskReponseDigest` 
- Update `SignedTaskResponseDigest` to return the `TaskResponse` rather than the `TaskResponseDigest`
- Compute the `TaskResponseDigest` to be signed in the function as the hashFunction of the `TaskResponse` bytes
TODO: update comments
=> minimal diff to be able to return the task response bytes instead of just the task response digest

cmd/egnkey/derive_operatorid/derive_operatorid.go, cmd/egnkey/generate/generate.go, cmd/egnkey/main.go, cmd/egnkey/operatorid/operatorid.go, cmd/egnkey/store/store.go
Not sure if this is the best place to have this but I really need something like this to help me debug wrong operator registration scenarios for tests and local devnets.
Typically generate a bunch of keys from some mnemonic, and want to quickly see their associated operatorId (hash of G1 pubkey associated with that private key). So with this command I'll just be able to pipe the private keys through this to also print their operatorId
also refactored commands to be in their own packages to prevent var/flag conflicts
=> added derive_operatorid command to egnkey

chainio/clients/avsregistry/writer.go, types/operator.go
=> add UpdateSocket fn to avs writer client

services/bls_aggregation/blsagg.go, services/bls_aggregation/blsagg_test.go, services/mocks/blsagg/blsaggregation.go, types/avs.go
the hashfn type in blsagg was not returning error, which was forcing implementations to panic.
Updated to also return error so client can decide what to do on error
=> Update blsagg service hash fn to return error

services/bls_aggregation/blsagg.go, services/bls_aggregation/blsagg_test.go
Add task index in the BlsAggregationServiceResponse when error
When develop aggregator by eigensdk-go, some bls sig task may failed or expired, when this happend, 
the caller will got a err from `blsAggServ.aggregatedResponsesC`.
But this responses will just contain a err by:
```go
TaskExpiredErrorFn = func(taskIndex types.TaskIndex) error {
return fmt.Errorf("task %d expired", taskIndex)
}
```
if the caller should process which task is failed, only can write this code:
```go
var taskIndex uint32
if blsAggServiceResp.Err != nil {
errString := blsAggServiceResp.Err.Error()
if strings.Contains(errString, "expired") {
fmt.Sscanf(errString, "task %d expired", &taskIndex)
t.logger.Debug("expired index", "index", taskIndex)
}
} else {
taskIndex = blsAggServiceResp.TaskIndex
}
// process …
```
=> feat: Add task index in the BlsAggregationServiceResponse when error

chainio/clients/avsregistry/reader.go, chainio/clients/elcontracts/writer.go, chainio/mocks/elContractsWriter.go, cmd/egnkey/main.go, signerv2/kms_signer.go
Fixes # .
- Separate 2 different actions so client can only have dedicated tx and save on gas. Earlier this method used to send 2 transactions so I separated them
- formatting
- logging fixes
=> separate operator details and metadata uri update

services/bls_aggregation/blsagg.go
Fixes # .
Fixed the race condition when accessing the `signedTaskRespsCs` map.
=> fix: race condition on blsagg
